#!/bin/bash
# VPS 上自动提交新数据到 Git 的脚本

cd "$(dirname "$0")/.." || exit 1

# 检查是否有新数据
if [[ -n $(git status --porcelain data/newly_scraped/) ]]; then
    # 获取当前月份
    MONTH=$(date +%B)
    YEAR=$(date +%Y)

    # 添加新数据文件
    git add data/newly_scraped/

    # 提交
    git commit -m "chore: update NBA data for ${MONTH} ${YEAR}

- Auto-scraped monthly data
- Timestamp: $(date +'%Y-%m-%d %H:%M:%S')
- Generated by: scrape_latest.py on VPS"

    # 推送到远程（需要配置 SSH key）
    git push origin main

    echo "✅ Data committed and pushed successfully"
else
    echo "ℹ️  No new data to commit"
fi
